/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MealRouteImport } from './routes/meal'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DoneRouteImport } from './routes/done'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as WorkoutIdRouteImport } from './routes/workout.$id'
import { Route as TrainerIdRouteImport } from './routes/trainer.$id'
import { Route as OnboardingWhatsappRouteImport } from './routes/onboarding.whatsapp'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiLiveCoachRouteImport } from './routes/api/live-coach'
import { Route as CoachSummarySessionIdRouteImport } from './routes/coach.summary.$sessionId'
import { Route as CoachSessionSessionIdRouteImport } from './routes/coach.session.$sessionId'
import { Route as ApiCoachTtsRouteImport } from './routes/api/coach/tts'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MealRoute = MealRouteImport.update({
  id: '/meal',
  path: '/meal',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneRoute = DoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIdRoute = WorkoutIdRouteImport.update({
  id: '/workout/$id',
  path: '/workout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIdRoute = TrainerIdRouteImport.update({
  id: '/trainer/$id',
  path: '/trainer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWhatsappRoute = OnboardingWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => OnboardingRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveCoachRoute = ApiLiveCoachRouteImport.update({
  id: '/api/live-coach',
  path: '/api/live-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachSummarySessionIdRoute = CoachSummarySessionIdRouteImport.update({
  id: '/coach/summary/$sessionId',
  path: '/coach/summary/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachSessionSessionIdRoute = CoachSessionSessionIdRouteImport.update({
  id: '/coach/session/$sessionId',
  path: '/coach/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachTtsRoute = ApiCoachTtsRouteImport.update({
  id: '/api/coach/tts',
  path: '/api/coach/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/done': typeof DoneRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/meal': typeof MealRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/ready': typeof ReadyRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/stats': typeof StatsRoute
  '/trainers': typeof TrainersRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/live-coach': typeof ApiLiveCoachRoute
  '/api/tts': typeof ApiTtsRoute
  '/onboarding/whatsapp': typeof OnboardingWhatsappRoute
  '/trainer/$id': typeof TrainerIdRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/coach/': typeof CoachIndexRoute
  '/api/coach/tts': typeof ApiCoachTtsRoute
  '/coach/session/$sessionId': typeof CoachSessionSessionIdRoute
  '/coach/summary/$sessionId': typeof CoachSummarySessionIdRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/done': typeof DoneRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/meal': typeof MealRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/ready': typeof ReadyRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/stats': typeof StatsRoute
  '/trainers': typeof TrainersRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/live-coach': typeof ApiLiveCoachRoute
  '/api/tts': typeof ApiTtsRoute
  '/onboarding/whatsapp': typeof OnboardingWhatsappRoute
  '/trainer/$id': typeof TrainerIdRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/coach': typeof CoachIndexRoute
  '/api/coach/tts': typeof ApiCoachTtsRoute
  '/coach/session/$sessionId': typeof CoachSessionSessionIdRoute
  '/coach/summary/$sessionId': typeof CoachSummarySessionIdRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/done': typeof DoneRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/meal': typeof MealRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/ready': typeof ReadyRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/stats': typeof StatsRoute
  '/trainers': typeof TrainersRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/live-coach': typeof ApiLiveCoachRoute
  '/api/tts': typeof ApiTtsRoute
  '/onboarding/whatsapp': typeof OnboardingWhatsappRoute
  '/trainer/$id': typeof TrainerIdRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/coach/': typeof CoachIndexRoute
  '/api/coach/tts': typeof ApiCoachTtsRoute
  '/coach/session/$sessionId': typeof CoachSessionSessionIdRoute
  '/coach/summary/$sessionId': typeof CoachSummarySessionIdRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/done'
    | '/history'
    | '/live'
    | '/meal'
    | '/onboarding'
    | '/player'
    | '/profile'
    | '/progress'
    | '/ready'
    | '/rewards'
    | '/settings'
    | '/splash'
    | '/stats'
    | '/trainers'
    | '/whatsapp'
    | '/api/live-coach'
    | '/api/tts'
    | '/onboarding/whatsapp'
    | '/trainer/$id'
    | '/workout/$id'
    | '/coach/'
    | '/api/coach/tts'
    | '/coach/session/$sessionId'
    | '/coach/summary/$sessionId'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/done'
    | '/history'
    | '/live'
    | '/meal'
    | '/onboarding'
    | '/player'
    | '/profile'
    | '/progress'
    | '/ready'
    | '/rewards'
    | '/settings'
    | '/splash'
    | '/stats'
    | '/trainers'
    | '/whatsapp'
    | '/api/live-coach'
    | '/api/tts'
    | '/onboarding/whatsapp'
    | '/trainer/$id'
    | '/workout/$id'
    | '/coach'
    | '/api/coach/tts'
    | '/coach/session/$sessionId'
    | '/coach/summary/$sessionId'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/done'
    | '/history'
    | '/live'
    | '/meal'
    | '/onboarding'
    | '/player'
    | '/profile'
    | '/progress'
    | '/ready'
    | '/rewards'
    | '/settings'
    | '/splash'
    | '/stats'
    | '/trainers'
    | '/whatsapp'
    | '/api/live-coach'
    | '/api/tts'
    | '/onboarding/whatsapp'
    | '/trainer/$id'
    | '/workout/$id'
    | '/coach/'
    | '/api/coach/tts'
    | '/coach/session/$sessionId'
    | '/coach/summary/$sessionId'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  DoneRoute: typeof DoneRoute
  HistoryRoute: typeof HistoryRoute
  LiveRoute: typeof LiveRoute
  MealRoute: typeof MealRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PlayerRoute: typeof PlayerRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ReadyRoute: typeof ReadyRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRoute
  SplashRoute: typeof SplashRoute
  StatsRoute: typeof StatsRoute
  TrainersRoute: typeof TrainersRoute
  WhatsappRoute: typeof WhatsappRoute
  ApiLiveCoachRoute: typeof ApiLiveCoachRoute
  ApiTtsRoute: typeof ApiTtsRoute
  TrainerIdRoute: typeof TrainerIdRoute
  WorkoutIdRoute: typeof WorkoutIdRoute
  CoachIndexRoute: typeof CoachIndexRoute
  ApiCoachTtsRoute: typeof ApiCoachTtsRoute
  CoachSessionSessionIdRoute: typeof CoachSessionSessionIdRoute
  CoachSummarySessionIdRoute: typeof CoachSummarySessionIdRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal': {
      id: '/meal'
      path: '/meal'
      fullPath: '/meal'
      preLoaderRoute: typeof MealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$id': {
      id: '/workout/$id'
      path: '/workout/$id'
      fullPath: '/workout/$id'
      preLoaderRoute: typeof WorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/$id': {
      id: '/trainer/$id'
      path: '/trainer/$id'
      fullPath: '/trainer/$id'
      preLoaderRoute: typeof TrainerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/whatsapp': {
      id: '/onboarding/whatsapp'
      path: '/whatsapp'
      fullPath: '/onboarding/whatsapp'
      preLoaderRoute: typeof OnboardingWhatsappRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-coach': {
      id: '/api/live-coach'
      path: '/api/live-coach'
      fullPath: '/api/live-coach'
      preLoaderRoute: typeof ApiLiveCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/summary/$sessionId': {
      id: '/coach/summary/$sessionId'
      path: '/coach/summary/$sessionId'
      fullPath: '/coach/summary/$sessionId'
      preLoaderRoute: typeof CoachSummarySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/session/$sessionId': {
      id: '/coach/session/$sessionId'
      path: '/coach/session/$sessionId'
      fullPath: '/coach/session/$sessionId'
      preLoaderRoute: typeof CoachSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach/tts': {
      id: '/api/coach/tts'
      path: '/api/coach/tts'
      fullPath: '/api/coach/tts'
      preLoaderRoute: typeof ApiCoachTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingWhatsappRoute: typeof OnboardingWhatsappRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingWhatsappRoute: OnboardingWhatsappRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  DoneRoute: DoneRoute,
  HistoryRoute: HistoryRoute,
  LiveRoute: LiveRoute,
  MealRoute: MealRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PlayerRoute: PlayerRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ReadyRoute: ReadyRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRoute,
  SplashRoute: SplashRoute,
  StatsRoute: StatsRoute,
  TrainersRoute: TrainersRoute,
  WhatsappRoute: WhatsappRoute,
  ApiLiveCoachRoute: ApiLiveCoachRoute,
  ApiTtsRoute: ApiTtsRoute,
  TrainerIdRoute: TrainerIdRoute,
  WorkoutIdRoute: WorkoutIdRoute,
  CoachIndexRoute: CoachIndexRoute,
  ApiCoachTtsRoute: ApiCoachTtsRoute,
  CoachSessionSessionIdRoute: CoachSessionSessionIdRoute,
  CoachSummarySessionIdRoute: CoachSummarySessionIdRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
